app = "discord-amibot"
primary_region = "lax"

[build]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
